name: Publish release package (SmallsOnline.Web.Lib)
on:
  push:
    tags: [ 'v*.*.*' ]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    name: Build and publish
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup dotnet SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json

      - name: Configure GitHub package registry source
        run: dotnet nuget add source --username Smalls1652 --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/Smalls1652/index.json"

      - name: Run dotnet restore
        run: dotnet restore ./src/SmallsOnline.Web.Lib/
      
      - name: Create package
        run: dotnet pack ./src/SmallsOnline.Web.Lib/ --configuration Release --no-restore --output .

      - name: Publish package
        run: dotnet nuget push "*.nupkg" --source github --api-key ${{ secrets.GITHUB_TOKEN }}